//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Trabajo_1Entities3 : DbContext
    {
        public DB_Trabajo_1Entities3()
            : base("name=DB_Trabajo_1Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tTR_Categoria> tTR_Categoria { get; set; }
        public virtual DbSet<tTR_Producto> tTR_Producto { get; set; }
        public virtual DbSet<tTR_Proveedor> tTR_Proveedor { get; set; }
        public virtual DbSet<tTR_Roles> tTR_Roles { get; set; }
        public virtual DbSet<tTR_Usuarios> tTR_Usuarios { get; set; }
    }
}
