//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTR_Usuarios
    {
        public int iIdUsuario { get; set; }
        public Nullable<int> iIdRol { get; set; }
        public string vNombreUsuario { get; set; }
        public string vPassword { get; set; }
        public string vNombre { get; set; }
        public string vApellidos { get; set; }
        public Nullable<int> iEstado { get; set; }
        public string sRutaImagen { get; set; }
    
        public virtual tTR_Roles tTR_Roles { get; set; }
    }
}
