//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTR_Roles
    {
        public tTR_Roles()
        {
            this.tTR_Usuarios = new HashSet<tTR_Usuarios>();
        }
    
        public int iIdUsuario { get; set; }
        public string vNombreRol { get; set; }
        public Nullable<int> iEstado { get; set; }
        public int iEstadoEliminar { get; set; }
        public virtual ICollection<tTR_Usuarios> tTR_Usuarios { get; set; }
    }
}
