//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTR_Producto
    {
        public int iIdProducto { get; set; }
        public Nullable<int> iIdCategoria { get; set; }
        public string vNombreProducto { get; set; }
        public string vDescripcionProducto { get; set; }
        public Nullable<decimal> nPrecioCompra { get; set; }
        public Nullable<decimal> nPrecioVenta { get; set; }
        public Nullable<int> iStockActual { get; set; }
        public Nullable<int> iStockMinimo { get; set; }
        public Nullable<int> iEstado { get; set; }
        public Nullable<int> iIdProveedor { get; set; }
    
        public virtual tTR_Categoria tTR_Categoria { get; set; }
        public virtual tTR_Proveedor tTR_Proveedor { get; set; }
    }
}
